# Site settings
title: Daily Me
name: Dannion Qiu
email: dannionqiu@gmail.com
description: "I come. I see. I eat."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: rdiscount
permalink: pretty

